refactor: make the dockerfile input generic

diff --git a/.github/workflows/docker-workflow.yml b/.github/workflows/docker-workflow.yml
--- a/.github/workflows/docker-workflow.yml
+++ b/.github/workflows/docker-workflow.yml
@@ -3,6 +3,9 @@ name: docker-workflow
 on:
   workflow_call:
     inputs:
+      dockerfile:
+        required: true
+        type: string
       image_name:
         required: true
         type: string
@@ -10,9 +13,6 @@ on:
         required: true
         type: string
       datadog_label:
-        required: false
-        type: string
-      dockerfile:
         required: false
         type: string
     secrets:
@@ -29,44 +29,50 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Checkout tools
-      uses: actions/checkout@v3
-      with:
-        repository: onlydustxyz/cicd
-        path: onlydust-cicd-tools
+      - name: Checkout tools
+        uses: actions/checkout@v3
+        with:
+          repository: onlydustxyz/cicd
+          path: onlydust-cicd-tools
 
-    - name: Copy rocket-rs Dockerfile
-      if: inputs.dockerfile == 'rocket-rs'
-      run: |
-        cp $GITHUB_WORKSPACE/onlydust-cicd-tools/dockerfiles/rocket-rs/Dockerfile $GITHUB_WORKSPACE/Dockerfile
+      - name: Verify the dockerfile exists
+        run: |
+          if [ ! -d "$GITHUB_WORKSPACE/onlydust-cicd-tools/dockerfiles/${{ inputs.dockerfile }}" ]; then
+            echo "Dockerfile ${{ inputs.dockerfile }} not found in shared repository"
+            exit 1
+          fi
 
-    - name: Login to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Copy docker files
+        run: |
+          cp -r $GITHUB_WORKSPACE/onlydust-cicd-tools/dockerfiles/${{ inputs.dockerfile }}/* $GITHUB_WORKSPACE/
 
-    - name: Build the Docker image
-      id: build-image
-      env:
-        DOCKER_REPOSITORY: ${{ inputs.image_name }}
-        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
-        IMAGE_TAG: ${{ inputs.image_tag }}
-        DATADOG_LABEL: ${{ inputs.datadog_label }}
-      run: |
-        echo "Building docker image $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
-        docker build --build-arg DATADOG_LABEL="$DATADOG_LABEL" -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
-        echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Push the image to Docker Hub
-      id: push-image
-      env:
-        IMAGE: ${{ steps.build-image.outputs.image }}
-      run: |
-        echo "Pushing image $IMAGE to Docker Hub..."
-        docker push $IMAGE
-        echo "Done"
-        echo "::set-output name=image::$IMAGE"
+      - name: Build the Docker image
+        id: build-image
+        env:
+          DOCKER_REPOSITORY: ${{ inputs.image_name }}
+          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
+          IMAGE_TAG: ${{ inputs.image_tag }}
+          DATADOG_LABEL: ${{ inputs.datadog_label }}
+        run: |
+          echo "Building docker image $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
+          docker build --build-arg DATADOG_LABEL="$DATADOG_LABEL" -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
+          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
+
+      - name: Push the image to Docker Hub
+        id: push-image
+        env:
+          IMAGE: ${{ steps.build-image.outputs.image }}
+        run: |
+          echo "Pushing image $IMAGE to Docker Hub..."
+          docker push $IMAGE
+          echo "Done"
+          echo "::set-output name=image::$IMAGE"
